name: Pull Request Build

on:
  pull_request:
    branches:
      - master

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build-make-linux
      uses: docker://golang:1.18.4
      with:
        args: -c "make check test"
        entrypoint: /bin/sh
